// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6mrGCyajHVlk6NQaKW1ddze3qKA8xbo',
    appId: '1:403186135178:web:f510b84415a0cff6167d73',
    messagingSenderId: '403186135178',
    projectId: 'restaurant-5b40a',
    authDomain: 'restaurant-5b40a.firebaseapp.com',
    storageBucket: 'restaurant-5b40a.appspot.com',
    measurementId: 'G-D4LFJCCGEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiQRqqyY21d25m1yq2wbn9wfnEsBu9-ZA',
    appId: '1:403186135178:android:9488bd5a838575d9167d73',
    messagingSenderId: '403186135178',
    projectId: 'restaurant-5b40a',
    storageBucket: 'restaurant-5b40a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh5Abcuxy_BmGd1hzqE8EWPtkp77ZjBkw',
    appId: '1:403186135178:ios:250f728bd1d8e4bd167d73',
    messagingSenderId: '403186135178',
    projectId: 'restaurant-5b40a',
    storageBucket: 'restaurant-5b40a.appspot.com',
    iosBundleId: 'com.wahdanz.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh5Abcuxy_BmGd1hzqE8EWPtkp77ZjBkw',
    appId: '1:403186135178:ios:250f728bd1d8e4bd167d73',
    messagingSenderId: '403186135178',
    projectId: 'restaurant-5b40a',
    storageBucket: 'restaurant-5b40a.appspot.com',
    iosBundleId: 'com.wahdanz.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ6mrGCyajHVlk6NQaKW1ddze3qKA8xbo',
    appId: '1:403186135178:web:854d257815e4821e167d73',
    messagingSenderId: '403186135178',
    projectId: 'restaurant-5b40a',
    authDomain: 'restaurant-5b40a.firebaseapp.com',
    storageBucket: 'restaurant-5b40a.appspot.com',
    measurementId: 'G-47P4GM35XK',
  );

}